name: Build CD-HIT

on:
  push:
    # Publish `$default-branch` as Docker `latest` image.
    branches:
      - dev
      - master
    paths: 
      - software/nibscbioinformatics/cd-hit/Dockerfile
      - software/nibscbioinformatics/cd-hit/environment.yml
      - .github/workflows/cd-hit_build.yml

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  SOFTWARE: cd-hit
  VERSION: v4.8.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          IMAGETAGGED=ghcr.io/nibscbioinformatics/$SOFTWARE:$VERSION
          docker build --tag $IMAGETAGGED ./containers/$SOFTWARE/.

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ secrets.GITPACKAGE_USER }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          IMAGETAGGED=ghcr.io/nibscbioinformatics/$SOFTWARE:$VERSION
          docker push $IMAGETAGGED
