name: Build Reporting

on:
  push:
    branches:
      - dev
    paths:
      - software/local/report/Dockerfile
      - software/local/report/environment.yml
      - .github/workflows/reporting_container_build.yml

env:
  # TODO: Change variable to your image's name.
  SOFTWARE: nibscreporting
  VERSION: v1.00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          IMAGETAGGED=ghcr.io/nibscbioinformatics/$SOFTWARE:$VERSION
          docker build --tag $IMAGETAGGED ./software/local/report/.

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ secrets.GITPACKAGE_USER }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          IMAGETAGGED=ghcr.io/nibscbioinformatics/$SOFTWARE:$VERSION
          docker push $IMAGETAGGED
